name: nlp
channels:
  - defaults
dependencies:
  - python=3.11.4
  - numpy
  - pytorch
  - conda-forge::transformers==4.27.2
  - conda-forge::accelerate==0.17.1
  - conda-forge::datasets==2.9.0
  - conda-forge::evaluate==0.4.0
  - conda-forge::peft==0.2.0
