name: nlp
channels:
  - defaults
dependencies:
  - python=3.11.4
  - numpy
  - pytorch
  - conda-forge::tensorboard
  - conda-forge::bitsandbytes
  - conda-forge::transformers
  - conda-forge::accelerate
  - conda-forge::datasets
  - conda-forge::evaluate
  - conda-forge::peft
  - conda-forge::sentencepiece
  
